version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: hospital-postgres
    restart: always
    environment:
      POSTGRES_USER: hospital
      POSTGRES_PASSWORD: hospital123
      POSTGRES_DB: hospital_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-fhir-db.sql:/docker-entrypoint-initdb.d/init-fhir-db.sql

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

  hapi-fhir:
    image: hapiproject/hapi:v8.2.0-2
    container_name: hospital-fhir
    restart: always
    depends_on:
      - postgres
    ports:
      - "8081:8080"
    environment:
      spring.datasource.url: jdbc:postgresql://postgres:5432/fhir_db
      spring.datasource.username: hospital
      spring.datasource.password: hospital123
      spring.datasource.driverClassName: org.postgresql.Driver
      spring.jpa.properties.hibernate.dialect: ca.uhn.fhir.jpa.model.dialect.HapiFhirPostgresDialect
      hapi.fhir.default_encoding: json
      hapi.fhir.fhir_version: R4
      hapi.fhir.narrative_enabled: false

volumes:
  postgres_data:
