"""initial hospital schema

Revision ID: 1d1c8c99fcff
Revises: 
Create Date: 2026-09-30 01:13:37.485470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1d1c8c99fcff'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beds',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('bed_number', sa.String(), nullable=False),
    sa.Column('ward', sa.String(), nullable=False),
    sa.Column('room_number', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=False),
    sa.Column('floor', sa.String(), nullable=True),
    sa.Column('location_id', sa.String(), nullable=False),
    sa.Column('bed_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('gender_policy', sa.String(), nullable=True),
    sa.Column('oxygen', sa.Boolean(), nullable=True),
    sa.Column('ventilator', sa.Boolean(), nullable=True),
    sa.Column('isolation', sa.Boolean(), nullable=True),
    sa.Column('cardiac_monitor', sa.Boolean(), nullable=True),
    sa.Column('dialysis', sa.Boolean(), nullable=True),
    sa.Column('pediatric', sa.Boolean(), nullable=True),
    sa.Column('maternity', sa.Boolean(), nullable=True),
    sa.Column('cleaning_required', sa.Boolean(), nullable=True),
    sa.Column('occupied_by', sa.String(), nullable=True),
    sa.Column('encounter_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bed_number')
    )
    op.create_table('lab_templates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('test_code', sa.String(), nullable=False),
    sa.Column('test_name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('test_code')
    )
    op.create_table('laboratory_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('service_request_id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('encounter_id', sa.String(), nullable=True),
    sa.Column('practitioner_id', sa.String(), nullable=False),
    sa.Column('technician_id', sa.String(), nullable=True),
    sa.Column('test_code', sa.String(), nullable=False),
    sa.Column('test_name', sa.String(), nullable=False),
    sa.Column('priority', sa.Enum('ROUTINE', 'URGENT', 'STAT', name='priority'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SAMPLE_COLLECTED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='laborderstatus'), nullable=False),
    sa.Column('sample_status', sa.Enum('NOT_COLLECTED', 'COLLECTED', 'REJECTED', 'RECEIVED', name='samplestatus'), nullable=False),
    sa.Column('clinical_note', sa.Text(), nullable=True),
    sa.Column('ordered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_laboratory_orders_patient_id'), 'laboratory_orders', ['patient_id'], unique=False)
    op.create_index(op.f('ix_laboratory_orders_service_request_id'), 'laboratory_orders', ['service_request_id'], unique=True)
    op.create_table('practitioner_schedules',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('practitioner_id', sa.String(), nullable=False),
    sa.Column('day_of_week', sa.String(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('practitioner_id', 'day_of_week', 'start_time', 'end_time', name='uq_practitioner_schedule')
    )
    op.create_index(op.f('ix_practitioner_schedules_day_of_week'), 'practitioner_schedules', ['day_of_week'], unique=False)
    op.create_index(op.f('ix_practitioner_schedules_practitioner_id'), 'practitioner_schedules', ['practitioner_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('designation', sa.String(), nullable=True),
    sa.Column('practitioner_id', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_practitioner_id'), 'users', ['practitioner_id'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('bed_allocations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('bed_id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('encounter_id', sa.String(), nullable=False),
    sa.Column('allocated_by', sa.String(), nullable=True),
    sa.Column('allocation_type', sa.String(), nullable=True),
    sa.Column('recommendation_score', sa.Float(), nullable=True),
    sa.Column('recommendation_reason', sa.Text(), nullable=True),
    sa.Column('allocated_at', sa.DateTime(), nullable=True),
    sa.Column('released_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['bed_id'], ['beds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lab_parameters',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('template_id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('value_type', sa.String(), nullable=False),
    sa.Column('reference_low', sa.Float(), nullable=True),
    sa.Column('reference_high', sa.Float(), nullable=True),
    sa.Column('required', sa.Boolean(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['lab_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('laboratory_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('laboratory_order_id', sa.UUID(), nullable=False),
    sa.Column('diagnostic_report_id', sa.String(), nullable=False),
    sa.Column('service_request_id', sa.String(), nullable=False),
    sa.Column('generated_by', sa.String(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['laboratory_order_id'], ['laboratory_orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('diagnostic_report_id')
    )
    op.create_index(op.f('ix_laboratory_results_laboratory_order_id'), 'laboratory_results', ['laboratory_order_id'], unique=False)
    op.create_index(op.f('ix_laboratory_results_service_request_id'), 'laboratory_results', ['service_request_id'], unique=False)
    op.drop_index(op.f('checkpoints_thread_id_idx'), table_name='checkpoints')
    op.drop_table('checkpoints')
    op.drop_index(op.f('checkpoint_writes_thread_id_idx'), table_name='checkpoint_writes')
    op.drop_table('checkpoint_writes')
    op.drop_index(op.f('checkpoint_blobs_thread_id_idx'), table_name='checkpoint_blobs')
    op.drop_table('checkpoint_blobs')
    op.drop_table('checkpoint_migrations')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checkpoint_migrations',
    sa.Column('v', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('v', name=op.f('checkpoint_migrations_pkey'))
    )
    op.create_table('checkpoint_blobs',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('channel', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('version', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('blob', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'channel', 'version', name=op.f('checkpoint_blobs_pkey'))
    )
    op.create_index(op.f('checkpoint_blobs_thread_id_idx'), 'checkpoint_blobs', ['thread_id'], unique=False)
    op.create_table('checkpoint_writes',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('checkpoint_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('idx', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('channel', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('blob', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('task_path', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'checkpoint_id', 'task_id', 'idx', name=op.f('checkpoint_writes_pkey'))
    )
    op.create_index(op.f('checkpoint_writes_thread_id_idx'), 'checkpoint_writes', ['thread_id'], unique=False)
    op.create_table('checkpoints',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('checkpoint_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('parent_checkpoint_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('checkpoint', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'checkpoint_id', name=op.f('checkpoints_pkey'))
    )
    op.create_index(op.f('checkpoints_thread_id_idx'), 'checkpoints', ['thread_id'], unique=False)
    op.drop_index(op.f('ix_laboratory_results_service_request_id'), table_name='laboratory_results')
    op.drop_index(op.f('ix_laboratory_results_laboratory_order_id'), table_name='laboratory_results')
    op.drop_table('laboratory_results')
    op.drop_table('lab_parameters')
    op.drop_table('bed_allocations')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_practitioner_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_practitioner_schedules_practitioner_id'), table_name='practitioner_schedules')
    op.drop_index(op.f('ix_practitioner_schedules_day_of_week'), table_name='practitioner_schedules')
    op.drop_table('practitioner_schedules')
    op.drop_index(op.f('ix_laboratory_orders_service_request_id'), table_name='laboratory_orders')
    op.drop_index(op.f('ix_laboratory_orders_patient_id'), table_name='laboratory_orders')
    op.drop_table('laboratory_orders')
    op.drop_table('lab_templates')
    op.drop_table('beds')
    # ### end Alembic commands ###
